### PR TITLE
Fix translation token

### PR DESCRIPTION
**Pull request by zonky2**

### CODE REVIEW

**Review by fritzmg — CHANGES_REQUESTED** [review]
This cannot be correct, as the placeholder is `%record%`?

https://github.com/inspiredminds/contao-file-usage/blob/00a080d0cba0cc956c7920e5a25103610671661a/translations/ContaoFileUsage.en.yaml#L5

**Comment by zonky2** [comment]
no

**Comment by fritzmg** [comment]
You need to elaborate what you mean by "no".

**Comment by zonky2** [comment]
fixed...

**Review by fritzmg — APPROVED** [review]

**Pull request merged**
